import type { Config } from "tailwindcss";

const config: Config = {
  theme: {
    extend: {
      colors: {
        surface: "#131313",
        "surface-bright": "#393939",
        "on-secondary-fixed-variant": "#36485b",
        "surface-container-lowest": "#0e0e0e",
        "outline-variant": "#4e453d",
        "on-secondary": "#203243",
        "on-primary-fixed-variant": "#5f401a",
        "on-error": "#690005",
        "error-container": "#93000a",
        "primary-fixed": "#ffddb9",
        "primary-fixed-dim": "#ecbe8d",
        "secondary-fixed": "#d1e4fb",
        error: "#ffb4ab",
        "primary-container": "#b1895c",
        "on-secondary-container": "#a4b7cd",
        "on-surface-variant": "#d1c4ba",
        outline: "#9a8f85",
        "tertiary-fixed-dim": "#b8c8db",
        primary: "#ecbe8d",
        "surface-tint": "#ecbe8d",
        "inverse-primary": "#7a582f",
        "on-primary-container": "#3e2401",
        "on-primary-fixed": "#2b1700",
        "on-surface": "#e5e2e1",
        "on-tertiary-fixed-variant": "#394858",
        "on-background": "#e5e2e1",
        secondary: "#b5c8df",
        "on-secondary-fixed": "#091d2e",
        "tertiary-fixed": "#d3e4f8",
        "on-tertiary-container": "#1b2b3a",
        background: "#131313",
        "inverse-on-surface": "#313030",
        "on-tertiary": "#223241",
        "inverse-surface": "#e5e2e1",
        tertiary: "#b8c8db",
        "secondary-container": "#36485b",
        "on-primary": "#462a05",
        "surface-container-highest": "#353535",
        "tertiary-container": "#8292a4",
        "surface-variant": "#353535",
        "surface-container-high": "#2a2a2a",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#b5c8df",
        "surface-container": "#20201f",
        "surface-dim": "#131313",
        "surface-container-low": "#1c1b1b",
        "on-tertiary-fixed": "#0c1d2b",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Noto Serif"],
        body: ["Manrope"],
        label: ["Manrope"],
      },
    },
  },
};

export default config;
